services:
  oracle_database:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-local
    ports:
      - "host_port:1521"
      - "host_port:5500"
    environment:
      - ORACLE_SID=cdb-system-identifer
      - ORACLE_PDB=pdb-name
      - ORACLE_PWD=oracle-user-password
      - INIT_SGA_SIZE=cdb-database-sga-memory-in-mb
      - INIT_PGA_SIZE=cdb-database-pga-memory-in-mb
      - ORACLE_EDITION=ee-or-se-database-edition
      - ORACLE_CHARACTERSET=character-set
      - ENABLE_ARCHIVELOG=[true|false]
    volumes:
      - oracle_data:/opt/oracle/oradata:/opt/oracle/oradata
volumes:
  oracle_data:
