version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      POSTGRES_PASSWORD: supersecurepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
